In [102]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import numpy.random as nr
import sklearn.model_selection as ms
import math


%matplotlib inline

In [57]:
data = pd.read_json('https://raw.githubusercontent.com/wncc/learners-space/master/Machine%20Learning/MId%20Term%20Assignment/data.json')
data.head()

0         1  2
0 -3.005382 -1.701191  1
1 -2.908105 -1.699589  1
2 -2.958954 -1.660940  1
3 -2.922840 -1.638722  1
4 -2.924240 -1.508256  1

In [58]:
label_counts = data.iloc[:,2].value_counts()
print(label_counts)

1    4679
0    1321
Name: 2, dtype: int64


In [47]:
# labels = np.array(data.iloc[:, 2])

In [95]:
X = data.iloc[:,:2]
Y = data.iloc[:,2:]
x_train,x_test,y_train,y_test = ms.train_test_split(X,Y, test_size = 0.2)

0         1
0     9.032319  2.894050
1     8.457077  2.888604
2     8.755407  2.758720
3     8.542995  2.685411
4     8.551181  2.274836
...        ...       ...
5995  8.863178  2.166225
5996  8.924947  2.245966
5997  8.198303  2.381477
5998  8.580937  2.628916
5999  8.932123  2.488543

[6000 rows x 2 columns]

In [170]:
nr.seed(3432)
np.array(x_train).reshape(4800,2)
np.array(y_train).reshape(4800,1)



array([[0],
       [1],
       [0],
       ...,
       [1],
       [0],
       [0]])

In [112]:
print(x_train)

             0         1
2713 -0.371902 -1.251144
695  -2.461700  1.556300
2473 -0.643855  0.760351
5244  2.137680 -0.110429
3775  0.690295  0.829854
...        ...       ...
5172  2.047902  0.714714
4692  1.639363  1.388698
45   -2.993520 -0.144795
2311 -0.799276 -1.220207
3185  0.018570  1.196394

[4800 rows x 2 columns]


In [262]:
# Function  
def f(A, coef):
  fun = np.dot(A,coef.reshape(5,1))
  return fun

In [207]:
# Hypothesis
def h(A, coef):
  return np.array(1/(1+(np.exp(-f(A,coef)))) )

In [113]:
# Loss function
def l(y, A, coef):   # y shouldn't be the predicted values
  return (-np.dot(y, np.log(h(A, coef))) - np.dot((1-y),np.log(1-h(A, coef))) )/y.shape[0]

In [272]:
# Gradient 
def g(A, coef, y):
  return np.dot(np.array(h(A, coef).reshape(4800,1) - y).reshape([1,4800]), A)/y.shape[0]
  # here we will get a 1x5 matrix consisting of the gradient wrt each of the coeff

In [273]:
# Gradient Descent 
def gradesc(A, y, coef):       # here coef is column vector 
  for i in range (250):
    coef = coef.reshape(5,1) - g(A, coef, y).reshape(5,1)
  return coef  


In [167]:

A0 = np.array(x_train[0]**4).reshape(1, 4800)
A1 = np.array(x_train[0]**3 * x_train[1]).reshape(1, 4800)
A2 = np.array(x_train[0]**2 * x_train[1]**2).reshape(1, 4800)
A3 = np.array(x_train[0]**1 * x_train[1]**3).reshape(1, 4800)
A4 = np.array(x_train[1]**4 ).reshape(1, 4800)
A = np.vstack((A0, A1, A2, A3, A4))
A = A.T
print(A)
A.shape

[[ 1.91298605e-02  6.43563036e-02  2.16506221e-01  7.28366007e-01
   2.45035471e+00]
 [ 3.67232118e+01 -2.32166122e+01  1.46776672e+01 -9.27930017e+00
   5.86642350e+00]
 [ 1.71850800e-01 -2.02944770e-01  2.39664753e-01 -2.83028698e-01
   3.34238735e-01]
 ...
 [ 8.03024531e+01  3.88419512e+00  1.87876847e-01  9.08752230e-03
   4.39559545e-04]
 [ 4.08119830e-01  6.23052177e-01  9.51176558e-01  1.45210446e+00
   2.21684118e+00]
 [ 1.18913640e-07  7.66122030e-06  4.93587586e-04  3.18002480e-02
   2.04878688e+00]]


(4800, 5)

In [271]:
coef = np.array([0.001, 0.001, 0.001, 0.001, 0.001])
type(coef)
coef.shape

(5,)

In [277]:
gradesc(A,y_train, coef)

(5, 1)

array([0.001, 0.001, 0.001, 0.001, 0.001])

In [283]:
def predict(x_test, coef = gradesc(A,y_train, coef) ):
  A0 = np.array(x_test[0]**4).reshape(1, 1200)
  A1 = np.array(x_test[0]**3 * x_test[1]).reshape(1, 1200)
  A2 = np.array(x_test[0]**2 * x_test[1]**2).reshape(1, 1200)
  A3 = np.array(x_test[0]**1 * x_test[1]**3).reshape(1, 1200)
  A4 = np.array(x_test[1]**4 ).reshape(1, 1200)
  A = np.vstack((A0, A1, A2, A3, A4))
  A = A.T
  return h(A, coef)

In [284]:
predict(x_test)

array([[0.52059253],
       [0.20303665],
       [0.30886608],
       ...,
       [1.        ],
       [0.99999938],
       [0.99742771]])